import Head from 'next/head'
import axios from 'axios'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data, data2 }) {
  console.log(data.photo, '111')
  console.log(data2, '222')
  // export default function Home() {

  // const [state, setState] = useState()

  // useEffect(() => {
  //   axios.get(`http://localhost:3000/api`)
  //     .then(res => setState(res.data))
  // }, [])
  // console.log(state[0])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {(data ? data : data2).map(obj => <img src={obj.url} />)} */}
      {/* {state?.map(obj => <img key={obj.name} src={obj.url} />)} */}
      <main>
        {console.log(data, '12412412412214')}
        {data?.map(obj => {
          return <p key={obj.name}>
            <Link href={{ pathname: `/detail/${obj.name}` }}><img src={obj.url} /></Link>
          </p>
        })}
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await axios.get(`http://localhost:3000/api`)
  const data = res.data

  return { props: { data } }
}

// export async function getServerSideProps() {
//   const res = await axios.get(`http://localhost:3000/api/cup`)
//   const data2 = res.data

//   return { props: { data2 } }
// }